version: "3.4" 
networks:
  external:
  internal:
  auth:
services:    
  front-po:
    image: 192.168.0.8:5000/front-po:latest.master
    hostname: front-po
    ports:
      - "3001:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          memory: 512M
    networks:
      - internal
      - auth
      - external
  front-bo:
    hostname: front-bo
    image: 192.168.0.8:5000/front-bo:latest.master
    ports:
      - "3002:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          memory: 512M
    networks:
      - internal
      - auth
      - external



  
